import {eContractid, IReserveParams} from "../helpers/types";

import {
  rateStrategyStableTwo,
  rateStrategyStableThree,
  rateStrategyXETH,
  rateStrategyWBTC,
  rateStrategyAPE,
  rateStrategyNFT,
  rateStrategyParaSpace,
} from "./rateStrategies";
import {auctionStrategyExp} from "./auctionStrategies";

export const strategyDAI: IReserveParams = {
  strategy: rateStrategyStableTwo,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "7500",
  liquidationThreshold: "8000",
  liquidationBonus: "10500",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "18",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyUSDC: IReserveParams = {
  strategy: rateStrategyStableThree,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "8000",
  liquidationThreshold: "8500",
  liquidationBonus: "10500",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "6",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyUSDT: IReserveParams = {
  strategy: rateStrategyStableTwo,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "7500",
  liquidationThreshold: "8000",
  liquidationBonus: "10500",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "6",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyWETH: IReserveParams = {
  strategy: rateStrategyXETH,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "8250",
  liquidationThreshold: "8500",
  liquidationBonus: "10500",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "18",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyWBTC: IReserveParams = {
  strategy: rateStrategyWBTC,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "7000",
  liquidationThreshold: "7500",
  liquidationBonus: "10650",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "8",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "2000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategySTETH: IReserveParams = {
  strategy: rateStrategyXETH,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "6900",
  liquidationThreshold: "8100",
  liquidationBonus: "10750",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "18",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyAPE: IReserveParams = {
  strategy: rateStrategyAPE,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "2000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "18",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyAWETH: IReserveParams = {
  strategy: rateStrategyXETH,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "6900",
  liquidationThreshold: "8100",
  liquidationBonus: "10750",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "18",
  xTokenImpl: eContractid.PTokenAToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyCETH: IReserveParams = {
  strategy: rateStrategyXETH,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "6900",
  liquidationThreshold: "8100",
  liquidationBonus: "10750",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "8",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyPUNK: IReserveParams = {
  strategy: rateStrategyXETH,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "6900",
  liquidationThreshold: "8100",
  liquidationBonus: "10750",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "18",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyParaSpace: IReserveParams = {
  strategy: rateStrategyParaSpace,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "2000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  reserveDecimals: "18",
  xTokenImpl: eContractid.PToken,
  reserveFactor: "1000",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyBAYC: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyWPUNKS: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyMAYC: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyDOODLES: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyMoonbird: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyMeebits: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyAzuki: IReserveParams = {
  strategy: rateStrategyAPE,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyOthr: IReserveParams = {
  strategy: rateStrategyAPE,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyClonex: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: true,
  auctionRecoveryHealthFactor: "1500000000000000000",
};

export const strategyUniswapV3: IReserveParams = {
  strategy: rateStrategyNFT,
  auctionStrategy: auctionStrategyExp,
  baseLTVAsCollateral: "3000",
  liquidationThreshold: "7000",
  liquidationBonus: "10500",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  reserveDecimals: "0",
  xTokenImpl: eContractid.NToken,
  reserveFactor: "0",
  borrowCap: "0",
  supplyCap: "0",
  auctionEnabled: false,
  auctionRecoveryHealthFactor: "1500000000000000000",
};
